import type { PageServerLoad } from './$types';
import { PUBLIC_HOST } from '$env/static/public';
import { eq, or } from 'drizzle-orm';
import { sites_table, posts } from '$lib/schemas/db/schema';
import { error } from '@sveltejs/kit';
// import { BYPASS_TOKEN } from '$env/static/private';

// export const config = {
// 	isr: {
// 		// Expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
// 		// Setting the value to `false` means it will never expire.
// 		expiration: 60 * 5,

// 		// Random token that can be provided in the URL to bypass the cached version of the asset, by requesting the asset
// 		// with a __prerender_bypass=<token> cookie.
// 		//
// 		// Making a `GET` or `HEAD` request with `x-prerender-revalidate: <token>` will force the asset to be re-validated.
// 		bypassToken: BYPASS_TOKEN

// 		// List of valid query parameters. Other parameters (such as utm tracking codes) will be ignored,
// 		// ensuring that they do not result in content being regenerated unnecessarily
// 		// allowQuery: ['search']
// 	}
// };

export const load: PageServerLoad = async (event) => {
	const subdomain = event.url.host.replace(`.${PUBLIC_HOST}`, '');
	const custom_domain = event.url.host;

	const site = await event.locals.db.query.sites_table.findFirst({
		where: or(eq(sites_table.subdomain, subdomain), eq(sites_table.custom_domain, custom_domain)),
		columns: {
			name: true,
			description: true,
			cover_image_url: true,
			subdomain: true,
			custom_domain: true
		},
		with: {
			posts: {
				limit: 6,
				columns: {
					title: true,
					description: true,
					slug: true,
					created_at: true
				},
				where: eq(posts.published, true)
			}
		}
	});

	if (!site) error(404, 'Not found');

	return { site };
};
